language: generic
sudo: required
service:
  - docker

before_insatall:
  - docker build -t gtanagardigil/docker-react -f Dockerfile.dev .

script:
  - docker run gtanagardigil/docker-react npm run test -- --coverage