language: generic
sudo: required
service:
  - docker

before_insatall:
  - docker build -t gtanagardigil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gtanagardigil/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-316380125309"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"